export const localStorageKey = {
  LeftPanel: 'left-panel',
  threads: 'threads',
  messages: 'messages',
  theme: 'theme',
  modelProvider: 'model-provider',
  modelSources: 'model-sources',
  settingInterface: 'setting-appearance',
  settingGeneral: 'setting-general',
  settingCodeBlock: 'setting-code-block',
  settingLocalApiServer: 'setting-local-api-server',
  settingProxyConfig: 'setting-proxy-config',
  settingHardware: 'setting-hardware',
  settingVulkan: 'setting-vulkan',
  productAnalyticPrompt: 'productAnalyticPrompt',
  productAnalytic: 'productAnalytic',
  toolApproval: 'tool-approval',
  toolAvailability: 'tool-availability',
  mcpGlobalPermissions: 'mcp-global-permissions',
  lastUsedModel: 'last-used-model',
  lastUsedAssistant: 'last-used-assistant',
  defaultAssistantId: 'default-assistant-id',
  favoriteModels: 'favorite-models',
  setupCompleted: 'setup-completed',
  threadManagement: 'thread-management',
  modelSupportCache: 'parlo_model_support_cache',
  recentSearches: 'recent-searches',
  parloModelPromptDismissed: 'Parlo-model-prompt-dismissed',
  agentMode: 'agent-mode',
  latestParloModel: 'latest-Parlo-model',
  defaultEmbeddingModel: 'default-embedding-model',
  pausedDownloads: 'paused-downloads',
  chatSidePanel: 'chat-side-panel',
  workspacePanel: 'workspace-panel',
  workspaceDirectories: 'workspace-directories',
  chatWorkspaceContext: 'chat-workspace-context',
  chatSessionState: 'chat-session-state',
  runtimePermissions: 'runtime-permissions',
  codexProviderProfiles: 'codex-provider-profiles',
  codexHostFlags: 'codex-host-flags',
  terminalRuntime: 'terminal-runtime',
}

export const CACHE_EXPIRY_MS = 1000 * 60 * 60 * 24
