blank_issues_enabled: true
contact_links:
  - name: Parlo Discussions
    url: https://github.com/orgs/parlo-lab/discussions/categories/q-a
    about: Get help, discuss features & roadmap, and share your projects
